# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaf6e2546e98efc235fd7e90ca73636d62119b611fc9b3ed8be4f83ca8cdfd27a90b925a500ba126b49fd82bebf1cc80b040beb9332740991dde472d097178b1

test:
  secret_key_base: 8b24c881cb98ef38bb1afbc11b11afe7762a53405c33b46f2b359ee9273ed2b02e54a0725236400be341da442f9c9fe88689dae880cd21da4c836344e8610ad3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
